# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
compose = "1.7.3"
jme3 = "3.8.0-alpha2"
kotlin = "2.1.0"
kotlinxDatetime = "0.6.1"
kotlinxSerializationJSON = "1.7.2"
kotlinxCoroutines = "1.8.1"
koin = "4.0.1"
voyager = "1.1.0-beta02"

[libraries]
jme3-core = { group = "org.jmonkeyengine", name = "jme3-core", version.ref = "jme3" }
jme3-desktop = { group = "org.jmonkeyengine", name = "jme3-desktop", version.ref = "jme3" }
jme3-effects = { group = "org.jmonkeyengine", name = "jme3-effects", version.ref = "jme3" }
jme3-lwjgl = { group = "org.jmonkeyengine", name = "jme3-lwjgl", version.ref = "jme3" }
jme3-lwjgl3 = { group = "org.jmonkeyengine", name = "jme3-lwjgl3", version.ref = "jme3" }
filekit = { group = "io.github.vinceglb", name = "filekit-compose", version = "0.8.8" }
kmidi = { group = "org.wysko", name = "kmidi", version = "0.1.1" }
compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version = "2.4.2" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version = "0.72.0" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
voyager-navigator = { group = "cafe.adriel.voyager", name = "voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { group = "cafe.adriel.voyager", name = "voyager-screenmodel", version.ref = "voyager" }
voyager-transitions = { group = "cafe.adriel.voyager", name = "voyager-transitions", version.ref = "voyager" }
voyager-koin = { group = "cafe.adriel.voyager", name = "voyager-koin", version.ref = "voyager" }
voyager-tab-navigator = { group = "cafe.adriel.voyager", name = "voyager-tab-navigator", version.ref = "voyager" }
multiplatformSettings = { group = "com.russhwolf", name = "multiplatform-settings", version = "1.3.0" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.16" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.1.0-alpha1" }

# Libraries can be bundled together for easier import
[bundles]
jme3 = ["jme3-core", "jme3-desktop", "jme3-effects"]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
koin = ["koin-core", "koin-compose", "koin-compose-viewmodel"]
voyager = ["voyager-navigator", "voyager-screenmodel", "voyager-transitions", "voyager-koin", "voyager-tab-navigator"]
logging = ["logback-classic", "slf4j-api"]

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-kotlin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }